language: node_js
node_js:
- '0.10'
before_install:
- cd web
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start > /dev/null &
- npm run update-webdriver
- sleep 1
script:
- node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  --browsers=Firefox
- node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
deploy:
  provider: heroku
  api_key:
    secure: TlsjyXKUahgFU4KA7tBbYifajqWY5ZRAROH8HcUwWE49o2TyOLeDWJq1xpytSUe1lSYZX6cEwX4jkwAi2xlaWvs1gNCSP1X+xH9bWxt5J7M7AtNo3KyvQJET7xmpGOK79cqS/97wvQFYiq4yBU72cku7dtujeZQRxVHLXTpz+ehlZCSe4Qy+JLsBA1osiQ1PNqR1gvUKJsP7Qf9NPWrnhVn0T9OTFVdtPYp7FvcqLcdK2nm0ARlAUfcDGPcLMqwtUed6jRpPcvac1hIHjcAVwRZOsvgZqtd50L4u0JrVzsnUulfyNwlvmiCB9APTzsX0m80BML6LCqXLU8yhSuTSdJBVjcEYCMWniWxvxKwyUczamjauaxZ54+r0XAj85L/Eaf9bl/CFz+Ufv80mvM61NVDE3j26+QS976uHAl2+8YIyKOnL0fLE9usRcClUEeVP/JYh3wntvPSkokGM5pvKbfgNAYot7iJyB60FLY1grqbDccxV3MS6YKMjFga+0deonBsR7Mel5Voj1qKQOdSuKriepGwiaCAndIizgoJRN3af8Z3c+wetEQj/s8ljyXNdQ82JL7VDlhXajRG7fmTku5TI1QuvYCb111VI+EmwnNXKFcg8o7gq5qop3Kz5GZuQKjxqUx4WfPRQRc7XNr57BzXdjeNvPXSJBRaIOe1qGDo=
    app: ondetemjogo