language: node_js
node_js:
- '0.10'
before_install:
- cd web
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start > /dev/null &
- npm run update-webdriver
- sleep 1
script:
- node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  --browsers=Firefox
- node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
deploy:
  provider: heroku
  api_key:
    secure: ns9owsfFyH/I6dN4hvwKzAp4bblxk+moKAbzVq93XCFJe7/y1xQNNhYcbVinXixs8i1lv1eJ9TzzqbFRw7E2SmVYGS4gJyXXdC//j+AR5G4L5xlkmqm9e9pdhcfXImvBDHZuZVDC4mrF1dLndoRu9Grc3Dw4Ek4d68mtQRvlq95uM8d0ygHba8xkcHUPIaWlkkCPtPpaDQ6BJQqORO15x5oF+iFBbZ4k/5XBwYiKRhZG4N7e3BYmFyKNpX3QaW9I9dPuY7jCnPwswIg2qfukMZ07BiM/RmdKb97syxzu21wFmduzYcayC9evlI+6aw/IPvEItHuz9Hwq1fjl+tAMHeEwjDnJqQjHdqVSCOmkFF86LFsL4MJSjDOTQQU6uSH/V4GGCzDfnbqYDvPJoXZNN8bKk2gqrliM8Jl5EYE6bGTKEiUeaATR4P9N5iBIoyBwoqLDe6eukPH2j4UxfGaQVM3PnvGruuQKxZKtygS24oYPXrmJDYDy+UMKz3FrFIcR57XO6vkuCdBXx33UFugjPnjM/rB3FaEhgerU5uMX+y2SCgzzROYPRfB5SY609ogkMLb4HFBDr+E8K/Tpc/nfvvvtnyS8a0frBoERQw+1Eq7IN/hG1MIABWceesltfqsFTKACp2Smijz1gRhEjrU4kgpbpHpUGBewBCHLq9k7D+4=
