language: node_js
node_js:
- '0.10'
before_install:
- cd web
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start > /dev/null &
- npm run update-webdriver
- sleep 1
script:
- node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  --browsers=Firefox
- node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
deploy:
  provider: heroku
  api_key:
    secure: qA+0SwYqrdZmowe/Pxv4fW1C5KGIeA2U+x+e+KHg6Oy7EjyjEE5nQHRN/NqALQBsDxdhaoUZl5w3E1pKSiD7fZpkoOTFEyB0yyq1an9rsstqj6GvbCN0mNsZI+AKLkmL9ePF6hOvtVkIzkmU/P6tIt3nvH5VPujNv5riW0E3eAlNJnEtSynpVEppYC8sVxtR0VEbi+xv9fz86wG2yLYfv1bRPWJV12fVJUADSGQcX2Wui1U3wAdDwSFpI3IOuofx5+JuLC96qdGK2JSbUz58tYF066eAsTz7PoyuhR8cMrZFR5RtXoYBRbPa36czVJ3a1Fu/5Ss+ZDqidG8mQuZLl0Mj08ZwyIruL+p6zwOxEXOwb37fb/6YZxWw/he40FWttk5wnYNg8M2aZCxKTp+e/YkiyIhxwZuqgfDoBqmbBTtbZ4g7tqZrRp7MA7T7DdXhv8Le+y0oouCr5SuGxDpCygNCTNXcM+VYlm6ENCFAZW2T7oWdREsTyKTusgmrxnYTwChRUbVP2a9DKGT03oQXz6LRFs7ugKdomXOrXElkvSonOqs8+fq7LebI29RX+l5LrE/p0+WF5AgvfmhjtoMw7dJO7/2FKOZaDTWJLvvyRVYZ5svK2hzTca9YxLIuayyebVq/A2D22taIYqJa22E1ioXoCDmQhZSyRRpcFv/GpkY=
    app: ondetemjogo