language: node_js
node_js:
- '0.10'
before_install:
- cd web
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start > /dev/null &
- npm run update-webdriver
- sleep 1
script:
- node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  --browsers=Firefox
- node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
deploy:
  provider: heroku
  api_key:
    secure: "mstz8chtKnlPD9Rf2UDxvtH9naNem0Gb0Se0nzNxr7N/NxcNf0wIyW9ojenzEwG46G0IaDVjRuPrRiSFdT7wJn8auZe5culBu64Vrb2shzONvzkygB9SJWbQSCY7Gvk48bWUz+1y0uMG7xqCddoY27IdD+7gJHIy1QPyvNwwKn9s7nerBgjcnnfiqoWMDlyaKT/b72JiWtoeGLYE7pY7+PPoHkzY8bZBHXQmNasLeJaNdHyxJzG7FJoR26EsSyvxG3atK+w9A6Co8rbR2eal610OxOMcIYQUBqchomstxkYVCunsEoyU0oRxZBhjBNy2Fu6+wezAfg7EgENHb7V4wOD1wl5ptsW3sQEOvbImUj16IlP2d25/dF336FSQ0Ugy+enW3PBrIJCRfCPwtBtS/tp+9UVQ8mitU3OcPrUIqiOcpuMYOLjrlgXak2I4LDbLM2pZ/y/PS3+yb3EqBtG6U8S4DUGNmT1py3MA5xTMRKz6YzLCQK8OgU94aGkBj0u2meNzk06xlqIfh0GNbpB5IZB2KgqCZfRSEcmTci+09ZoGcu70G5Vc6xBMISmMVPAdQ7kNN1dLYNUUPpbPplj7jQOA57kYOvMrioVAMLB381geN/rzDIza/RYXUeBmPBNJNR5kR3SfztrEdy+vHffGyFexY+FArefDm4NrFRmNE44="
  app: ondetemjogo
  on:
    repo: ProjetoChernobyl/ondetemjogo